name: Publish to npm code artifact repository
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: catalystsquad/action-upload-npm-aws-codeartifact@v1
        with:
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.COMMON_CICD_ROLE_ARN }}
          domain: ${{ secrets.CODE_ARTIFACT_DOMAIN }}
          domain-owner: ${{ secrets.CODE_ARTIFACT_DOMAIN_OWNER }}
